#!/bin/bash
# Diff an package from the overlay with its version in the Portage tree

if [[ $# != 1 || "$1" == "-h" || "$1" == "--help" ]]
then
    echo "  Usage: ${0##*/} <package>
Print a diff of the given package between its overlay and Portage versions."
    exit
fi

diff -rq ${0%/*}/$1 /usr/portage/$1

